# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0003_auto_20170929_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
